name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APKs
        run: ./gradlew clean assembleDebug assembleRelease -x test

      - name: Prepare apk folder
        run: |
          mkdir -p apk
          cp app/build/outputs/apk/debug/*.apk apk/app-debug.apk || true
          cp app/build/outputs/apk/release/*.apk apk/app-release.apk || true

      - name: Upload debug APK (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: ignore

      - name: Upload release APK (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: ignore

      - name: Commit APKs into repo
        uses: EndBug/add-and-commit@v9
        with:
          add: 'apk/*.apk'
          author_name: github-actions
          author_email: actions@github.com
          message: 'chore(ci): add built APKs to apk folder'
          push: true
